version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 4001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./localdata/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4002:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
   # Default credentials - admin:pass
