[project]
name = "shelfspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fake-useragent>=2.2.0",
    "pydantic>=2.12.4",
    "requests>=2.32.5",
    "ruff>=0.14.4",
    "typer>=0.20.0",
]
